// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace RecommendedTendersForUsers
{
    public partial class TestAlgorithms
    {
        /// <summary>
        /// model input class for TestAlgorithms.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"PurchaseTypeId")]
            public float PurchaseTypeId { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"BeginPriceId")]
            public float BeginPriceId { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"SysModule")]
            public float SysModule { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Categories")]
            public float Categories { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"RegionId")]
            public float RegionId { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"OrganizationId")]
            public float OrganizationId { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"ProductsKtru")]
            public string ProductsKtru { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Estimation")]
            public float Estimation { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TestAlgorithms.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"PurchaseTypeId")]
            public float PurchaseTypeId { get; set; }

            [ColumnName(@"BeginPriceId")]
            public float BeginPriceId { get; set; }

            [ColumnName(@"SysModule")]
            public float SysModule { get; set; }

            [ColumnName(@"Categories")]
            public float Categories { get; set; }

            [ColumnName(@"RegionId")]
            public float RegionId { get; set; }

            [ColumnName(@"OrganizationId")]
            public float OrganizationId { get; set; }

            [ColumnName(@"ProductsKtru")]
            public float[] ProductsKtru { get; set; }

            [ColumnName(@"Estimation")]
            public float Estimation { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TestAlgorithms.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
